basePath: /
definitions:
  models.Product:
    type: object
info:
  contact: {}
  description: Esta é a documentação da API de Produtos
  title: API de Produtos
  version: "1.0"
paths:
  /products:
    post:
      consumes:
      - application/json
      description: Adiciona um novo produto ao banco de dados
      parameters:
      - description: Produto
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cria um novo produto
      tags:
      - produtos
swagger: "2.0"
